import { Lato } from "next/font/google";
import { AuthProvider } from "@/lib/context/AuthContext";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function ({ children }) {
  return (
    <html lang="es" data-theme="light">
      <body className={lato.className}>
        <AuthProvider>{children}</AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
